name        : accountsservice
version     : 0.6.40
release     : 8
source      :
    - http://www.freedesktop.org/software/accountsservice/accountsservice-0.6.40.tar.xz : f04f756600cbab558671658ab8e77212de2a000c07bc0469e7b51541871fcb2b
homepage    : http://www.freedesktop.org/wiki/Software/AccountsService
license     : GPL-3.0+
summary     : D-Bus service for accessing user accounts and information
builddeps   :
    - vala
description : |
    AccountsService is a D-Bus service for accessing the list of user accounts and information attached to those accounts.
setup      : |
    %configure --prefix=/usr \
                         --sysconfdir=/etc \
                         --localstatedir=/var \
                         --libexecdir=/usr/lib/accountsservice \
                         --enable-vala \
                         --enable-introspection \
                         --enable-systemd \
                         --disable-static
build      : |
    %make
install    : |
    %make_install
