name       : accountsservice
version    : 0.6.55
release    : 26
source     :
    - https://www.freedesktop.org/software/accountsservice/accountsservice-0.6.55.tar.xz : ff2b2419a7e06bd9cb335ffe391c7409b49a0f0130b890bd54692a3986699c9b
homepage   : http://www.freedesktop.org/wiki/Software/AccountsService
license    : GPL-3.0-or-later
component  : desktop.core
summary    : D-Bus service for accessing user accounts and information
description: |
    AccountsService is a D-Bus service for accessing the list of user accounts and information attached to those accounts.
builddeps  :
    - pkgconfig(gtk-doc)
    - vala
setup      : |
    %patch -p1 < $pkgfiles/0001-Support-automatic-login-for-LightDM-in-a-stateless-c.patch
    %patch -p1 < $pkgfiles/0001-Change-passwd-path-to-bin-since-that-is-where-our-bi.patch
    %meson_configure -Dadmin_group=sudo -Dextra_admin_groups="adm,lpadmin" -Dsystemd=true -Dgtk_doc=true
build      : |
    %ninja_build
install    : |
    %ninja_install
