name       : accountsservice
version    : 0.6.42
release    : 15
source     :
    - https://www.freedesktop.org/software/accountsservice/accountsservice-0.6.42.tar.xz : e56494c2f18627900b57234e5628923cc16a37bf8fd16b06c46118d6ae9c007e
homepage   : http://www.freedesktop.org/wiki/Software/AccountsService
license    : GPL-3.0+
summary    : D-Bus service for accessing user accounts and information
builddeps  :
    - vala
description: |
    AccountsService is a D-Bus service for accessing the list of user accounts and information attached to those accounts.
setup      : |
    %patch -p1 < $pkgfiles/0001-add-lightdm-support.patch
    %patch -p1 < $pkgfiles/0001-Support-use-of-default-Solus-groups.patch
    %configure --prefix=/usr \
                         --sysconfdir=/etc \
                         --localstatedir=/var \
                         --libexecdir=/usr/lib/accountsservice \
                         --enable-vala \
                         --enable-introspection \
                         --enable-systemd \
                         --enable-admin-group=sudo \
                         --disable-static
build      : |
    %make
install    : |
    %make_install
