name       : accountsservice
version    : 0.6.45
release    : 24
source     :
    - https://www.freedesktop.org/software/accountsservice/accountsservice-0.6.45.tar.xz : fb0fc293aa75d59f5ef5db719d37a21831c4dd74a97526ee7e51ce936311ef26
homepage   : http://www.freedesktop.org/wiki/Software/AccountsService
license    : GPL-3.0
component  : desktop.core
summary    : D-Bus service for accessing user accounts and information
description: |
    AccountsService is a D-Bus service for accessing the list of user accounts and information attached to those accounts.
builddeps  :
    - vala
setup      : |
    %patch -p1 < $pkgfiles/0001-Support-automatic-login-for-LightDM-in-a-stateless-c.patch
    %patch -p1 < $pkgfiles/0001-Support-use-of-default-Solus-groups.patch
    %patch -p1 < $pkgfiles/0001-Change-passwd-path-to-bin-since-that-is-where-our-bi.patch
    %configure --prefix=/usr --disable-static \
        --sysconfdir=/etc \
        --localstatedir=/var \
        --libexecdir=/usr/lib/accountsservice \
        --enable-vala \
        --enable-introspection \
        --enable-systemd \
        --enable-admin-group=sudo
build      : |
    %make
install    : |
    %make_install
