name       : accountsservice
version    : 0.6.45
release    : 20
source     :
    - https://www.freedesktop.org/software/accountsservice/accountsservice-0.6.45.tar.xz : fb0fc293aa75d59f5ef5db719d37a21831c4dd74a97526ee7e51ce936311ef26
homepage   : http://www.freedesktop.org/wiki/Software/AccountsService
license    : GPL-3.0+
component  : desktop.core
summary    : D-Bus service for accessing user accounts and information
builddeps  :
    - vala
description: |
    AccountsService is a D-Bus service for accessing the list of user accounts and information attached to those accounts.
setup      : |
    %patch -p1 < $pkgfiles/0001-Support-automatic-login-for-LightDM-in-a-stateless-c.patch
    %patch -p1 < $pkgfiles/0001-Support-use-of-default-Solus-groups.patch
    %configure --prefix=/usr \
                         --sysconfdir=/etc \
                         --localstatedir=/var \
                         --libexecdir=/usr/lib/accountsservice \
                         --enable-vala \
                         --enable-introspection \
                         --enable-systemd \
                         --enable-admin-group=sudo \
                         --disable-static
build      : |
    %make
install    : |
    %make_install
